# Load all required packages used for this projects ----------------------------
library(pracma)
library(tools)
library(plotrix)

# Alphebetized packages --------------------------------------------------------
# I've commented out the libraries I do not believe I'm using anymore
library(anytime)
library(animation)
library(abind)
library(bookdown)
library(car)

library(cmocean)
#library(dplyr)
library(data.table)
library(doParallel)
library(foreach)
#library(ggmap)
library(ggplot2)
library(gridExtra)
library(IndexNumR)
library(imputeTS)
library(kableExtra)
library(latex2exp)
library(mgcv)
library(modelr)
library(mgcViz)
library(ncdf4)
library(oce)
#library(plotly)
#library(processx)
library(parallel)
library(reshape2)
library(rworldmap)
#library(rworldxtra)
#library(rasterVis)
#library(rmatio)
library(rgeos)
library(remotes)
library(remote)
library(rgdal)
library(raster)
library(spatialEco)
library(stlplus)
library(sp)
library(sf)
library(Thermimage)
library(tidyverse)
library(viridis)
library(zoo)
library(rerddap)
library(RColorBrewer)
#library(lattice)






